import React from 'react';
import {
  cover,
  orderOfService,
  biography,
  widowTribute,
  childrenTribute,
  grandchildrenTribute,
  greatGrandchildrenTribute,
  inlawsTribute,
  programOutline,
  momoSupport,
} from '../../data/brochureContent.js';
import portraitImg from '../../assets/main page/portrait.png';
import supportImg from '../../assets/main page/support.jpeg';

/* ─────────────────────────────────────────────────────────────────────────────
   Vite glob imports – resolved cleanly at build-time using modern specs
   ───────────────────────────────────────────────────────────────────────────── */
const galleryRaw  = import.meta.glob('../../assets/Gallery/*.{jpg,jpeg,png,JPG,PNG}',       { eager: true, query: '?url', import: 'default' });
const childrenRaw = import.meta.glob('../../assets/Children/*.{jpg,jpeg,png,JPG,PNG}',      { eager: true, query: '?url', import: 'default' });
const wifeRaw     = import.meta.glob('../../assets/Wife/*.{jpg,jpeg,png,JPG,PNG}',          { eager: true, query: '?url', import: 'default' });
const grandRaw    = import.meta.glob('../../assets/Grand Children/*.{jpg,jpeg,png,JPG,PNG}', { eager: true, query: '?url', import: 'default' });
const greatRaw    = import.meta.glob('../../assets/Great Grand children/*.{jpg,jpeg,png,JPG,PNG}', { eager: true, query: '?url', import: 'default' });
const inlawsRaw   = import.meta.glob('../../assets/Inlaws/*.{jpg,jpeg,png,JPG,PNG}',        { eager: true, query: '?url', import: 'default' });

/* ─────────────────────────────────────────────────────────────────────────────
   Image helpers
   ───────────────────────────────────────────────────────────────────────────── */
const looksAutoGenerated = (name) =>
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(name) ||
  /^\d{8,}_status_/.test(name) ||
  /^IMG-\d{8}-WA\d+$/i.test(name) ||
  /^FB_IMG_\d+$/i.test(name) ||
  /^WhatsApp Image/i.test(name) ||
  /^\d{4}-\d{2}-\d{2}$/.test(name);

const toPhotos = (raw, fallbackPrefix = 'Photo') => {
  const items = Object.entries(raw).map(([path, url]) => {
    const filename = path.split('/').pop().replace(/\.[^.]+$/, '');
    const cleaned  = filename.replace(/^\d+\.\s*/, '').trim();
    return { url, filename, caption: looksAutoGenerated(cleaned) ? '' : cleaned };
  });
  items.sort((a, b) =>
    a.filename.localeCompare(b.filename, undefined, { numeric: true })
  );
  let n = 1;
  return items.map((item) => ({
    ...item,
    caption: item.caption || `${fallbackPrefix} ${n++}`,
  }));
};

const galleryPhotos       = toPhotos(galleryRaw,  'Photo');
const wifePhotos          = toPhotos(wifeRaw,     'Photo');
const grandchildrenPhotos = toPhotos(grandRaw,    'Photo');
const greatGrandPhotos    = toPhotos(greatRaw,    'Photo');
const inlawsPhotos        = toPhotos(inlawsRaw,   'Photo');
// children folder contains a .rar archive – exclude non-image entries
const childrenPhotos = toPhotos(childrenRaw).filter(
  (p) => !/\.rar$/i.test(p.filename)
);

/* ─────────────────────────────────────────────────────────────────────────────
   Table of Contents definition
   ───────────────────────────────────────────────────────────────────────────── */
const TOC_ITEMS = [
  { id: 'order-of-service',            label: 'Order of Service' },
  { id: 'biography',                   label: 'Biography' },
  {
    id: 'widow-tribute', label: 'Tribute from Widow',
    sub: [{ id: 'widow-photos', label: 'Pictures with Widow' }],
  },
  {
    id: 'children-tribute', label: 'Tribute from Children',
    sub: [{ id: 'children-photos', label: 'Pictures of and with Children' }],
  },
  {
    id: 'grandchildren-tribute', label: 'Tribute from Grandchildren',
    sub: [{ id: 'grandchildren-photos', label: 'Pictures of and with Grandchildren' }],
  },
  {
    id: 'great-grandchildren-tribute', label: 'Tribute from Great-Grandchildren',
    sub: [{ id: 'great-grandchildren-photos', label: 'Pictures of and with Great-Grandchildren' }],
  },
  {
    id: 'inlaws-tribute', label: 'Tribute from In-Laws',
    sub: [{ id: 'inlaws-photos', label: 'Pictures of In-Laws' }],
  },
  { id: 'gallery',         label: 'Gallery — Nana Okru Baah' },
  { id: 'momo-support',   label: 'MoMo Support' },
  { id: 'program-outline', label: 'Program Outline' },
];

const scrollTo = (id) =>
  document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' });

/* ─────────────────────────────────────────────────────────────────────────────
   Reusable primitives
   ───────────────────────────────────────────────────────────────────────────── */

/** Section card with crimson header bar */
function BrochureSection({ id, label, number, children }) {
  return (
    <section className="brochure-section" id={id}>
      <div className="bs-header">
        <span className="bs-number">{number}</span>
        <h2 className="bs-title">{label}</h2>
      </div>
      <div className="bs-body">{children}</div>
    </section>
  );
}

/** Responsive photo grid — shows full photos without truncation */
function PhotoGrid({ photos }) {
  if (!photos.length) {
    return <p className="photo-empty">Photos coming soon.</p>;
  }
  return (
    <div className={`photo-grid ${photos.length > 14 ? 'photo-grid--dense' : ''}`}>
      {photos.map((p, i) => (
        <div key={`${p.url}-${i}`} className="photo-item">
          <img src={p.url} alt={p.caption} loading="lazy" />
          <p className="photo-caption">{p.caption}</p>
        </div>
      ))}
    </div>
  );
}

/** Tribute text with optional scripture block and sign-off */
function TributeText({ tribute }) {
  const paras = tribute.body.trim().split(/\n{2,}/).map((s) => s.trim()).filter(Boolean);
  return (
    <div className="tribute-text">
      {tribute.subtitle && tribute.scripture && (
        <blockquote className="scripture-block">
          <cite className="scripture-ref">{tribute.subtitle}</cite>
          <p className="scripture-body">{tribute.scripture}</p>
        </blockquote>
      )}
      <div className="tribute-body">
        {paras.map((para, i) => (
          <p key={i} className={i === 0 ? 'tribute-first-para' : ''}>
            {para}
          </p>
        ))}
      </div>
      {tribute.signoff && (
        <div className="tribute-signoff">
          <p className="tribute-farewell">— {tribute.signoff}</p>
          {tribute.signatory && (
            <p className="tribute-signatory">{tribute.signatory}</p>
          )}
        </div>
      )}
    </div>
  );
}

/* ─────────────────────────────────────────────────────────────────────────────
   COVER PAGE — Full-bleed portrait with text overlay
   ───────────────────────────────────────────────────────────────────────────── */
function CoverPage() {
  return (
    <div className="cover-page" id="cover">
      <img
        src={portraitImg}
        alt="Nana Okru-Baah V"
        className="cover-portrait-img"
      />
      <div className="cover-overlay">
        <div className="cover-top">
          <p className="cover-ornament">❖ ❖ ❖</p>
          <p className="cover-eyebrow">{cover.heading}</p>
        </div>
        <div className="cover-bottom">
          <h2 className="cover-name">{cover.fullName}</h2>
          <p className="cover-epithet">{cover.epithet}</p>
          <p className="cover-private-name">({cover.privateName})</p>
          <p className="cover-dates">{cover.birthDate} — {cover.deathDate}</p>
          <div className="cover-service">
            <p className="cover-venue">{cover.serviceVenue}</p>
            <p className="cover-service-date">{cover.serviceDate} · {cover.serviceTime}</p>
          </div>
        </div>
      </div>
    </div>
  );
}

/* ─────────────────────────────────────────────────────────────────────────────
   TABLE OF CONTENTS (standalone sheet)
   ───────────────────────────────────────────────────────────────────────────── */
function TocPage() {
  return (
    <div className="a5-sheet toc-sheet" id="table-of-contents">
      <div className="bp-column bp-column--toc">
        <h3 className="bp-section-title">Table of Contents</h3>
        <nav aria-label="Brochure contents" className="toc-list">
          {TOC_ITEMS.map((item, i) => (
            <div key={item.id} className="toc-item-group">
              <button
                type="button"
                className="toc-item toc-item--main"
                onClick={() => scrollTo(item.id)}
              >
                <span className="toc-letter">{String.fromCharCode(97 + i)}.</span>
                <span className="toc-label">{item.label}</span>
              </button>
              {item.sub?.map((sub) => (
                <button
                  key={sub.id}
                  type="button"
                  className="toc-item toc-item--sub"
                  onClick={() => scrollTo(sub.id)}
                >
                  <span className="toc-roman">i.</span>
                  <span className="toc-label">{sub.label}</span>
                </button>
              ))}
            </div>
          ))}
        </nav>
      </div>
    </div>
  );
}

/* ─────────────────────────────────────────────────────────────────────────────
   Main exported booklet
   ───────────────────────────────────────────────────────────────────────────── */
export function BrochureBooklet() {
  return (
    <div className="brochure-booklet-container">

      {/* ── Cover: Full-bleed portrait ─────────────────────────────────────── */}
      <CoverPage />

      {/* ── Table of Contents ──────────────────────────────────────────────── */}
      <TocPage />

      {/* ── I. Order of Service ────────────────────────────────────────────── */}
      <BrochureSection id="order-of-service" label="Order of Service" number="I">
        <div className="bp-timeline">
          {orderOfService.map((item, i) => (
            <div key={i} className="bp-timeline-row">
              <span className="bp-timeline-time">{item.time}</span>
              <div className="bp-timeline-content">
                <span className="bp-timeline-title">{item.title}</span>
                {item.presenter && (
                  <span className="bp-timeline-presenter">{item.presenter}</span>
                )}
              </div>
            </div>
          ))}
        </div>
      </BrochureSection>

      {/* ── II. Biography ──────────────────────────────────────────────────── */}
      <BrochureSection id="biography" label="Biography" number="II">
        <div className="bp-bio-flow">
          {biography
            .trim()
            .split(/\n{2,}/)
            .map((para, i) => (
              <p key={i} className={i === 0 ? 'bp-first-para' : ''}>
                {para.trim()}
              </p>
            ))}
        </div>
      </BrochureSection>

      {/* ── III. Tribute from Widow ────────────────────────────────────────── */}
      <BrochureSection
        id="widow-tribute"
        label={widowTribute.title}
        number="III"
      >
        <TributeText tribute={widowTribute} />
      </BrochureSection>

      <BrochureSection
        id="widow-photos"
        label="Pictures with Widow"
        number="III · i"
      >
        <PhotoGrid photos={wifePhotos} />
      </BrochureSection>

      {/* ── IV. Tribute from Children ──────────────────────────────────────── */}
      <BrochureSection
        id="children-tribute"
        label={childrenTribute.title}
        number="IV"
      >
        {/* Roll of children's names */}
        <div className="children-roll">
          {childrenTribute.children.map((c, i) => (
            <span key={i} className="child-name">{c}</span>
          ))}
        </div>
        <TributeText tribute={childrenTribute} />
      </BrochureSection>

      <BrochureSection
        id="children-photos"
        label="Pictures of and with Children"
        number="IV · i"
      >
        <PhotoGrid photos={childrenPhotos} />
      </BrochureSection>

      {/* ── V. Tribute from Grandchildren ─────────────────────────────────── */}
      <BrochureSection
        id="grandchildren-tribute"
        label={grandchildrenTribute.title}
        number="V"
      >
        <TributeText tribute={grandchildrenTribute} />
      </BrochureSection>

      <BrochureSection
        id="grandchildren-photos"
        label="Pictures of and with Grandchildren"
        number="V · i"
      >
        <PhotoGrid photos={grandchildrenPhotos} />
      </BrochureSection>

      {/* ── VI. Tribute from Great-Grandchildren ──────────────────────────── */}
      <BrochureSection
        id="great-grandchildren-tribute"
        label={greatGrandchildrenTribute.title}
        number="VI"
      >
        <TributeText tribute={greatGrandchildrenTribute} />
      </BrochureSection>

      <BrochureSection
        id="great-grandchildren-photos"
        label="Pictures of and with Great-Grandchildren"
        number="VI · i"
      >
        <PhotoGrid photos={greatGrandPhotos} />
      </BrochureSection>

      {/* ── VII. Tribute from In-Laws ──────────────────────────────────────── */}
      <BrochureSection
        id="inlaws-tribute"
        label={inlawsTribute.title}
        number="VII"
      >
        <TributeText tribute={inlawsTribute} />
      </BrochureSection>

      <BrochureSection
        id="inlaws-photos"
        label="Pictures of In-Laws"
        number="VII · i"
      >
        <PhotoGrid photos={inlawsPhotos} />
      </BrochureSection>

      {/* ── VIII. Gallery ──────────────────────────────────────────────────── */}
      <BrochureSection
        id="gallery"
        label="Gallery — Nana Okru Baah"
        number="VIII"
      >
        <PhotoGrid photos={galleryPhotos} />
      </BrochureSection>

      {/* ── IX. MoMo Support — Image + Link Only ──────────────────────────── */}
      <BrochureSection id="momo-support" label={momoSupport.heading} number="IX">
        <div className="momo-simple">
          <a
            href="https://korbapay.korba365.com/payments/institution/628?branch"
            target="_blank"
            rel="noopener noreferrer"
            className="momo-image-link"
            title="Tap to open payment page"
          >
            <img
              src={supportImg}
              alt="MoMo Support — Tap to Pay"
              className="momo-hero-image"
            />
          </a>
          <a
            href="https://korbapay.korba365.com/payments/institution/628?branch"
            target="_blank"
            rel="noopener noreferrer"
            className="momo-pay-btn"
          >
            Click Here to Send Support →
          </a>
        </div>
      </BrochureSection>

      {/* ── X. Program Outline ────────────────────────────────────────────── */}
      <BrochureSection
        id="program-outline"
        label="Program Outline"
        number="X"
      >
        <div className="program-grid">
          {programOutline.map((day, di) => (
            <div key={di} className="program-day">
              <h3 className="program-day-title">{day.day}</h3>
              <div className="program-events">
                {day.events.map((ev, ei) => (
                  <div key={ei} className="program-event">
                    <span className="program-time">{ev.time}</span>
                    <span className="program-desc">{ev.desc}</span>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </BrochureSection>

    </div>
  );
}